# String Formatting Tips

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Some sample data

x = np.random.rand(10,5)
x[:,0] = 1000000 * x[:,0]
x[:,1] = 1000 * x[:,1]
x[:,3] = .001 * x[:,3]
x[:,4] = .000001 * x[:,4]

df = pd.DataFrame(x)

In [4]:
print(x)

[[2.53895778e+04 7.24265247e+02 2.43807790e-01 9.78334606e-05
  5.98117018e-07]
 [1.28258899e+04 3.69300023e+02 4.52452845e-01 4.89530835e-04
  1.01241491e-07]
 [2.86389641e+05 5.65658753e+02 4.04146138e-01 4.17624894e-04
  2.36871777e-07]
 [1.53351311e+05 3.55891564e+02 6.89722420e-01 3.74713038e-04
  7.32469123e-07]
 [8.89558602e+05 4.94433274e+02 3.49785284e-01 6.47203161e-05
  6.77041932e-07]
 [1.08177416e+05 3.59629933e+02 6.93734745e-01 5.03594008e-04
  4.27963691e-07]
 [4.12008907e+05 1.96754257e+02 4.70057788e-01 5.16341506e-04
  4.78926720e-07]
 [7.41444004e+05 6.74115183e+02 1.08613710e-01 7.65827250e-04
  6.51064785e-07]
 [1.10648667e+05 7.05891343e+02 3.73600347e-01 4.29780317e-04
  1.53815759e-07]
 [5.73103391e+05 3.12768957e+02 9.04718976e-01 2.86749072e-04
  8.62602321e-07]]


In [5]:
df.head()

0           1         2         3             4
0   25389.577787  724.265247  0.243808  0.000098  5.981170e-07
1   12825.889888  369.300023  0.452453  0.000490  1.012415e-07
2  286389.641110  565.658753  0.404146  0.000418  2.368718e-07
3  153351.311429  355.891564  0.689722  0.000375  7.324691e-07
4  889558.602064  494.433274  0.349785  0.000065  6.770419e-07

# With Numpy

In [7]:
np.set_printoptions(precision=3,suppress=True)

In [8]:
print(x)

[[ 25389.578    724.265      0.244      0.         0.   ]
 [ 12825.89     369.3        0.452      0.         0.   ]
 [286389.641    565.659      0.404      0.         0.   ]
 [153351.311    355.892      0.69       0.         0.   ]
 [889558.602    494.433      0.35       0.         0.   ]
 [108177.416    359.63       0.694      0.001      0.   ]
 [412008.907    196.754      0.47       0.001      0.   ]
 [741444.004    674.115      0.109      0.001      0.   ]
 [110648.667    705.891      0.374      0.         0.   ]
 [573103.391    312.769      0.905      0.         0.   ]]


In [9]:
# Maybe Better Still

In [10]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print(x)

[[ 25389.578  724.265  0.244  0.000  0.000]
 [ 12825.890  369.300  0.452  0.000  0.000]
 [ 286389.641  565.659  0.404  0.000  0.000]
 [ 153351.311  355.892  0.690  0.000  0.000]
 [ 889558.602  494.433  0.350  0.000  0.000]
 [ 108177.416  359.630  0.694  0.001  0.000]
 [ 412008.907  196.754  0.470  0.001  0.000]
 [ 741444.004  674.115  0.109  0.001  0.000]
 [ 110648.667  705.891  0.374  0.000  0.000]
 [ 573103.391  312.769  0.905  0.000  0.000]]


 # With Pandas

https://www.geeksforgeeks.org/formatting-integer-column-of-dataframe-in-pandas/

In [11]:
pd.options.display.float_format = '{:.2f}'.format

In [12]:
df

0      1    2    3    4
0  25389.58 724.27 0.24 0.00 0.00
1  12825.89 369.30 0.45 0.00 0.00
2 286389.64 565.66 0.40 0.00 0.00
3 153351.31 355.89 0.69 0.00 0.00
4 889558.60 494.43 0.35 0.00 0.00
5 108177.42 359.63 0.69 0.00 0.00
6 412008.91 196.75 0.47 0.00 0.00
7 741444.00 674.12 0.11 0.00 0.00
8 110648.67 705.89 0.37 0.00 0.00
9 573103.39 312.77 0.90 0.00 0.00